name: KitPvP
version: 1.0
main: com.github.caaarlowsz.mazemc.kitpvp.Main
commands:
  groupset:
  tempgroupset:
  builder:
  hrc:
  admin:
  aplicar:
  hg:
  loja:
  store:
  kit:
  1v1:
  evento:
  giveall:
  ip:
  semiyt:
  pro:
  removeall:
  score:
  fly:
  helpop:
  tag:
  taglist:
  fake:
  tp:
  gamemode:
  gm:
  spro:
  youtuber:
  chat:
  setholograma:
  sc:
  ban:
  tempban:
  kick:
  unban:
  givecoins:
  mute:
  ipban:
  tempmute:
  dica:
  aviso:
  report:
  set:
  spawn:
  groupbuilder:
  warp:
  speed1v1:
  tell:
   aliases: [msg]
  reidamesa:
  rdm:
  join:
  entrar:
  sair:
  leave:
  specs:
  ban:
  tempban:
  kick:
  pardon:
  mute:
  ipban:
  tempmute:
  bancheck:
  mutecheck:
  bc:
  account:
  inv:
  invsee:
  getip:
  horas:
  rank:
  ranks:
  ping:
  acc:
  tpall:
  vis:
  invis:
  removerhead:
  removerhat:
  removehead:
  removehat:
  manutencao:
  cage:
  autosoup:
  tphere:
  s:
  stopserver:
  kickall:
  monitorar:
  skit:
  dano:
  pvp:
  clearall:
  tweetar:
  head:
  addpermission:
  removepermission:
  check:
  givevip:
  giveyoutuber:
  givebuilder:
  givekit: